mail:
  image: catatnight/postfix
  ports:
    - "25:25"
  environment:
    - maildomain=mail.bosun.com
    - smtp_user=bosun:bosun

graphite:
  build: ./graphite/
  ports:
    - "80:80"
    - "2003-2004:2003-2004"
    - "2023-2024:2023-2024"

influxdb:
  image: tutum/influxdb:0.10
  ports:
    - "8083:8083"
    - "8086:8086"

statsd:
  build: ./statsd/
  ports:
    - "8125:8125/udp"
  links:
    - graphite
    - influxdb

statsd_producer:
  build: ./statsd_producer
  links:
    - statsd

bosun:
  build: ./bosun/
  ports:
    - "8070:8070"
    - "4242:4242"
  links:
    - graphite
    - mail

